### ISSUE TITLE
Showing All translation unused

### ISSUE THREAD

**Issue by shivamjuyal19** [mxmvshnvsk/i18n-unused#11]
i have setup the config.js as 
module.exports = {
    localesPath: 'src/locale',
    srcPath: 'src',
};
But, on running i18n-unused display-unused , its showing all translations as unused.

**Comment by mxmvshnvsk** [comment]
@shivamjuyal19 hi. It's hard to understand an issue without example, can u show code part with translations?

**Comment by shivamjuyal19** [comment]
@mxmvshnvsk I have 980 translations available in my json file. Few are unused. I have created my config.js in root folder. But while running the command, its displaying all 980 translations as unused, which is wrong.

PFA-
<img width="1154" alt="Screenshot 2021-11-25 at 12 25 27 PM" src="https://user-images.githubusercontent.com/25325653/143394616-e933c61e-2603-40d9-bc5f-969b507c5a65.png">

Do i need to create config.js inside my src folder?

**Comment by mxmvshnvsk** [comment]
@shivamjuyal19 yes, u should create config in project root folder, u can read it in main doc![image](https://user-images.githubusercontent.com/25287077/143395070-2d28bd09-95d4-4fa6-94f1-7d27af35ec9c.jpeg)

**Comment by shivamjuyal19** [comment]
@mxmvshnvsk I have created in project root folder only. Done accordingly main docs available in github only.

**Comment by mxmvshnvsk** [comment]
Ok, can u show me translations using in your code, where u use t('translation.something')?

**Comment by shivamjuyal19** [comment]
@mxmvshnvsk 

{textTransKey ? t(textTransKey, textTransObj) : text || ''}

**Comment by mxmvshnvsk** [comment]
@shivamjuyal19  i18n-unused is static analyzer. It means that your code should include static translation value at least in one place. If u get values on air, it can't be analyzed.

For optimization u may have a map:

```javascript
translations = {
  submitButton: 'translations.buttons.submit'
}
```

And use it in code:

```html
<div>
  {{ t(translations[textTransKey]) }}
</div>
```

**Comment by mxmvshnvsk** [comment]
@shivamjuyal19 can I close an issue?
