### ISSUE TITLE
Support react-i18next's Trans

### ISSUE THREAD

**Issue by dantman** [mxmvshnvsk/i18n-unused#12]
react-i18next supports a `<Trans i18nKey="key">...<Trans>` component used for messages with html/components as a part.

It would be nice of i18n-unused could find these by default.

**Comment by mxmvshnvsk** [comment]
@dantman, u can try update to `0.5.2` version, I added key in [this commit](https://github.com/mxmvshnvsk/i18n-unused/commit/85bbe361a9348e97978594c2770a34b0d3cd4238).
