### ISSUE TITLE
Don't mark plurals/context as unused

### ISSUE THREAD

**Issue by dantman** [mxmvshnvsk/i18n-unused#13]
i18n-unused currently marks plural messages as unused, even when the non-plural version is in use. Same goes for contextual messages.

For example in [i18next](https://www.i18next.com/translation-function/plurals) the keys `key_one`, `key_other` (formerly `key` and `key_plural`) were both used by `t('key', {count: n})`. i18n-unused would mark all of these except `key` as unused leading to plurals being potentially deleted.

It's also possible to include [context](https://www.i18next.com/translation-function/context) in message keys.

i18n-unused does have excludeKey. But we don't want to exclude these keys, we want `key_one` to be treated as equivalent to `key` so that if `key` stops being used `key_one` is properly deleted by `i18n-unused remove-unused`.

I understand plural handling isn't consistent and context is fully custom. So perhaps the best solution is either a regexp of suffixes to remove from keys or a function to map message keys to the key used in code.

**Comment by mxmvshnvsk** [comment]
Hi @dantman. That's good case, I'll implement it in next minor update.

**Comment by mxmvshnvsk** [comment]
In new [`0.6.0`](https://www.npmjs.com/package/i18n-unused/v/0.6.0) version now available [`context`](https://github.com/mxmvshnvsk/i18n-unused/commit/c0f6f081c9eaa525664086e3a11c9f50bc4a5823) option (`true` by default).
