### ISSUE TITLE
Have an ignoredPath option or multiple srcPath

### ISSUE THREAD

**Issue by blombard** [mxmvshnvsk/i18n-unused#14]
Hello and thank you for this package 🙂 

I'm using this tool in a `Nuxtjs` app and the folder structure is pretty flat meaning not everything is under `app` or equivalent.

I would like to run this tool against `/components`, `/pages`, ... But since I can't do that, I'm forced to use the root path.

The problem is that the tool is also running in my `node_modules` so it takes a lot a time and can add some noise to the result.

I was wondering if it was possible to add an `ignoredPath` option or that `srcPath` could take an array of string as argument?

I'm willing to help if you can give me a bit of context on where to start 🙂

**Comment by mxmvshnvsk** [comment]
Hi @blombard. Thx for interest. It's good idea, I'll implement this logic in next minor version on next week.

**Comment by mxmvshnvsk** [comment]
@blombard, u can try version [`0.7.0`](https://www.npmjs.com/package/i18n-unused/v/0.7.0), option `ignorePaths` available in this version.

**Comment by mxmvshnvsk** [comment]
@blombard thx for your pr, I added some comments.

**Comment by blombard** [comment]
Have you submitted your review?

**Comment by mxmvshnvsk** [comment]
Sorry, already submitted.
