### ISSUE TITLE
Dynamic keys are incorrectly marked as unused

### ISSUE THREAD

**Issue by victorloux** [mxmvshnvsk/i18n-unused#21]
Hi! I might be missing something, but I believe some keys are incorrectly reported as unused when they are in fact used as dynamic keys.

For example, in code I have some calls like this:

```
const errorTitle = I18n.t(`event.api.error.${errorClass}.title`);
```
```
return I18n.t(`type.gender.${id}`);
```

Running the CLI command `display-unused` will list keys like those below as being unused, even though they do get used by the code above, which will fill in the dynamic code with a value such as `errorClass` or `id`.

```
event.api.error.blocked.title
event.api.error.photoUploadLimit.title
event.api.error.photoUploadSize.title

type.gender.woman
type.gender.man
type.gender.nonBinary
```

Is there a mechanism to automatically mark those as used? This library does seem to support dynamic keys when finding missing keys, but it only seems to be one-way.

**Comment by mxmvshnvsk** [comment]
Hello. It's correct. i18n-unused is static analyze tool, it's mean, that code doesn't compiles, only read sources.

**Comment by victorloux** [comment]
Thanks. I understand that — I'm asking if there is a way to automatically exclude keys that match a dynamic pattern. For example auto-exclude keys containing `type.gender.` from being reported as missing or unused when seeing the pattern `type.gender.${id}`.

I don't really want to have it mark all these keys as 'unused' and delete them, when doing so would actually break my app, because they _are_ used. 

I know I'd then run the risk of having missing or unused keys within that scope, but it'd still be nice to have the option to auto-exclude dynamic keys from these reports, even accepting this risk.

**Comment by mxmvshnvsk** [comment]
Oh, ok. You can use option excludeKey in config. It may be strings array. For example: excludeKey: ['${gender}']. Translations, that will contain this substring will be ignored.

**Comment by mxmvshnvsk** [comment]
And if u use js output in your ci, u can ignore `dynamicKeys` and `totalDynamicCount` in result, see docs.
```javascript
{
  translations: [
    {
      filePath: 'src_file_path',
      staticKeys: ['missed_key'], // keys without ${} syntax
      dynamicKeys: ['missed_key'], // keys with ${} syntax
      staticCount: 1,
      dynamicCount: 1,
    },
  ],
  totalStaticCount: 1,
  totalDynamicCount: 1,
}
```

**Comment by mxmvshnvsk** [comment]
Auto-excluding for dynamic keys it's may be good feature. I'll make a note for future releases.

**Comment by victorloux** [comment]
Thanks 🙏 I knew I could manually exclude keys, didn't realise I could put a dynamic substring placeholder in there, that's useful.

And yes, I've seen that the output of the _missed_ keys gives a count of the dynamic keys it found, but it doesn't seem to find them for _unused_ keys which is what I was looking for. I can do without for now — thanks for the help!
