### ISSUE TITLE
[Question] How to parse a YAML locales file?

### ISSUE THREAD

**Issue by medihack** [mxmvshnvsk/i18n-unused#24]
First, I want to say thanks for this helpful tool! Unfortunately, I can't figure out how to parse a `YAML` locales file (which is directly supported by i18next). I set `localesExtensions` to use `yml` extension and then want to provide a custom parser. First I thought that I can use `localeFileParser` for that, but from looking at the source code it doesn't do what I first thought it does. Is this even possible somehow?

**Comment by medihack** [comment]
I took a second look at the source, and it doesn't seem to be currently possible. Would you accept a PR to allow to set a custom loader? How about an option named `localeFileLoader` with type definition `(filePath: string) => RecursiveStruct`?

**Comment by mxmvshnvsk** [comment]
Hi, thx for interest. It sounds good. I'll be glad for pr with custom loader =)
