### ISSUE TITLE
remove-unused command, not working on flat Translations

### ISSUE THREAD

**Issue by sikaili99** [mxmvshnvsk/i18n-unused#26]
I have keys in files such as `en-us.json`  and the keys are in flat translation format.
```js
{
"common.edit":{
  "text": "Edit",
  "note" : ""
},
...
}

```

`common.edit` has been used in a component like  ``` text: `${t("common.edit")}` ``` where `t` is imported from the translation file.

When I run i18n-unused display-unused `common.edit` is also displayed, although it has been used. I tried to mark unused keys, `common.edit`  and all the keys in the `.json` are all marked as unused.

```js 
     common.edit.text [UNUSED] undefined
     common.edit.note [UNUSED] undefined
```

When I run i18n-unused remove-unused `, no key is remove.

```js
// config i18n-unused.config.js
module.exports = {
  localesPath: 'src/localize/locales',
  srcPath: 'src',
};

```

I am not sure where I have gone wrong. Any help, I will appreciate.

**Comment by mxmvshnvsk** [comment]
Hi, sorry for long response. If case actual, can u share me your repo example for reproduce?

**Comment by sikaili99** [comment]
> Hi, sorry for long response. If case actual, can u share me your repo example for reproduce?

Hi, unfortunately, the repo is a private one. I used a Python script I created, but it didn't do a perfect job, I had to do some clean-up manually.

**Comment by mxmvshnvsk** [comment]
Ok, for future u can share me part with translation usage and example part in locale file, I can debug. Or if this issue not actual, just close one.

**Comment by sikaili99** [comment]
Okay, I will try to share some parts of the translation and usage.
