### ISSUE TITLE
Mark everything as UNUSED

### ISSUE THREAD

**Issue by IlliaHohniak-Hexa** [mxmvshnvsk/i18n-unused#27]
Hi. I just start using it and got strange behaviour - all keys are marked as UNUSED. 

My config: 
```
module.exports = {
    localesPath: 'public/locales/en',
    srcPath: 'src',
    flatTranslations: true,
};
```

Part of my translations file (it's path: public/locales):
```
  "Enough rest": "Enough rest"
  "onboardingFlow.obRest.option1": "Not enough rest",
  "onboardingFlow.obRest.option2": "Some sleep",
  "onboardingFlow.obRest.option3": "A good rest",
```

In the code keys are using in 3 ways: 
- `t('onboardingFlow.obRest.option1')`
- `<Trans i18nKey="onboardingFlow.obRest.option1" />`
- `<Trans>Enough rest</Trans>`

Some components get keys as props.

I use command `i18n-unused mark-unused`

**Comment by mxmvshnvsk** [comment]
Hi, u should look option translationKeyMatcher in docs

**Comment by IlliaHohniak-Hexa** [comment]
What about keys in other 2 cases? The tool should recognize them

**Comment by mxmvshnvsk** [comment]
It's public repo, can I try to run script?

**Comment by IlliaHohniak-Hexa** [comment]
unfortunately, it's private project. Can we do it in some other way?

**Comment by mxmvshnvsk** [comment]
I'l try later

**Comment by IlliaHohniak-Hexa** [comment]
Hi. Did you check it? Maybe we can arrange some call with screen-sharing?

**Comment by mxmvshnvsk** [comment]
Hi, I'll check it on weekends, too much work on weekdays. If it blocker for u, pr's always open, welcome.

**Comment by IlliaHohniak-Hexa** [comment]
Hi. Did you find some time for this problem?
(no, it's not a real blocker. Just a useful improvement)

**Comment by athammer** [comment]
This was happening me. To fix and debug the issue I just went into node_modules for this package and did some snooping into the `i18n-unused.cjs` file and saw the `matchKeys` var in the `collectUnusedTranslations` function was returning an empty array in each case. If that's the case for you, you need to update the translationKeyMatcher option in the config file.

For example I added `  translationKeyMatcher: /(?:__\('(.*)'\))/ig` as I'm looking for translations that look like `__('translations.are.awesome'),`. Make sure your regex is only taking the `translations.are.awesome` part.

**Comment by IlliaHohniak-Hexa** [comment]
@athammer  Hi. Thanks, it really helps me.

And I have one more question to you. 
If I have key `"Enough rest": "Enough rest"`. And in the code it looks like `<Trans>Enough rest</Trans>` (It the old method and we just don't have time to rewrite keys). 
How can I write down it in the RegExp? I use this `(<Trans>.*?<\/Trans>)` and it works fine in the service https://regex101.com
but it still marks such keys.

**Comment by mxmvshnvsk** [comment]
Hi, it's real problem with regexp, thx @athammer =)

**Comment by IlliaHohniak-Hexa** [comment]
Also, @mxmvshnvsk @athammer did you have cases with concatenated strings? For example, I have key 
`"onboardingFlow.feedbackAge.female.20.text"`
and in the code it looks like
``onboardingFlow.feedbackAge.${gender}.20.text``

So, the lib marked it as UNUSED. It's logical, but maybe you did something with it? Because I think only about adding something like ".concat." to such keys and use option excludeKey. 

And pls, look at updated comment above :)

**Comment by mxmvshnvsk** [comment]
@IlliaHohniak-Hexa, no, it's dynamic key matching, i18n-unused is static analyze tool.

**Comment by IlliaHohniak-Hexa** [comment]
@mxmvshnvsk Why it's RegExp problem? The error is in the lib files

**Comment by mxmvshnvsk** [comment]
It was response to problem in topic, default regexp ignored keys not in brackets and cases without space before `t()`

**Comment by mxmvshnvsk** [comment]
@IlliaHohniak-Hexa  Share me you regexp for reproduce in missed case

**Comment by IlliaHohniak-Hexa** [comment]
@mxmvshnvsk translationKeyMatcher: /(t\(.*?\))|(i18nKey=".*?")|(".*?")|('.*?')|(<Trans>.*?<\/Trans>)/gi

**Comment by mxmvshnvsk** [comment]
@IlliaHohniak-Hexa problem in regexp, after match file content we have next collection with your regexp:

```javascript
// my test code
t('onboardingFlow.obRest.option1')
<Trans i18nKey="onboardingFlow.obRest.option2" />
<Trans>Enough rest</Trans>

// output after parsing translations patterns
[ 't(', 't.', 'ti', 'Tr', 't.', 'ti', '<Trans>Enough rest</Trans>' ]
```

I'll add guard for this case, but it can affect to performance.

Second problem is replacer, by default tool provide regexp for searching value in rounded brackets.

Now available [v0.11.0](https://www.npmjs.com/package/i18n-unused/v/0.11.0), u can set option `missedTranslationParser`, it can be regexp or function, that parse value from token after matching with `translationKeyMatcher`. Now in tool available getting value from rounded brackets. In future I'll made more flexible way to parse values.

**Comment by mxmvshnvsk** [comment]
If issue isn't actual, please, close an issue.

**Comment by IlliaHohniak-Hexa** [comment]
@mxmvshnvsk I have error:  TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))

Like you said I use missedTranslationParser: /(t\(.*?\))|(i18nKey=".*?")|(".*?")|('.*?')|(<Trans>.*?<\/Trans>)/gi
And updated lib

**Comment by mxmvshnvsk** [comment]
Hi. Remove _g_ flag from RegExp.

**Comment by IlliaHohniak-Hexa** [comment]
The same error

**Comment by mxmvshnvsk** [comment]
Are u sure in this regexp? Did u test it in runtime console?

**Comment by IlliaHohniak-Hexa** [comment]
This is the same regexp as I used for translationKeyMatcher.

**Comment by IlliaHohniak-Hexa** [comment]
But I still don't understand, why I got such error. And what can I do to fix it? 

I thought you use same logic for the translationKeyMatcher, right? So regexp should find all cases it code as translationKeyMatcher do.
