### ISSUE TITLE
Processing commented out lines of code

### ISSUE THREAD

**Issue by RVitaly1978** [mxmvshnvsk/i18n-unused#7]
I think it would be convenient if there was an opportunity to choose whether to process the `translationKey` in the commented out lines of code

**Comment by mxmvshnvsk** [comment]
@RVitaly1978, yes, it will be convenient, perhaps in the future I will implement this feature. So far, most of the time is spent on writing tests. If you have ideas for implementation, I will be glad to see your PR =)

**Comment by asvae** [comment]
@RVitaly1978 feel free to implement the feature :).
